version: '3.6'

services:
  mysql:
    image: mariadb:${mysql_version}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_pw}
      - MYSQL_DATABASE=${mysql_db}
    command:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/mysql/conf.d/utf8.cnf
        [client]
        default-character-set=utf8mb4
        [mysql]
        default-character-set=utf8mb4
        [mysqld]
        collation-server=utf8mb4_unicode_ci
        init-connect='SET NAMES utf8mb4'
        character-set-server=utf8mb4
        EOF
        docker-entrypoint.sh mysqld

volumes:
  mysql_data:
