version: '3.6'

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - www_data:/var/www:rw
    networks:
      - traefik-public
      - default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${domain}`)"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https@docker"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_secure.rule=Host(`${domain}`)"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_secure.entrypoints=websecure"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_secure.tls.certresolver=http"
        - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
    command:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/nginx/conf.d/server_tokens.conf
        server_tokens off;
        EOF
        cat <<"EOF" > /etc/nginx/conf.d/default.conf
        server {
          listen       80;
          server_name _;

          charset utf-8;

          root /var/www/public;
          index  index.html index.htm index.php;

          access_log /var/www/logs/nginx/access.log;
          error_log /var/www/logs/nginx/error.log;

          include /var/www/configs/nginx/host.conf;

          location ~ \.php$$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$$;
                try_files $$fastcgi_script_name =404;

                set $$path_info $$fastcgi_path_info;
                fastcgi_param PATH_INFO $$path_info;

                fastcgi_index index.php;
                fastcgi_param  SCRIPT_FILENAME    $$document_root$$fastcgi_script_name;
                fastcgi_param  QUERY_STRING       $$query_string;
                fastcgi_param  REQUEST_METHOD     $$request_method;
                fastcgi_param  CONTENT_TYPE       $$content_type;
                fastcgi_param  CONTENT_LENGTH     $$content_length;

                fastcgi_param  SCRIPT_NAME        $$fastcgi_script_name;
                fastcgi_param  REQUEST_URI        $$request_uri;
                fastcgi_param  DOCUMENT_URI       $$document_uri;
                fastcgi_param  DOCUMENT_ROOT      $$document_root;
                fastcgi_param  SERVER_PROTOCOL    $$server_protocol;
                fastcgi_param  REQUEST_SCHEME     $$scheme;
                fastcgi_param  HTTPS              $$https if_not_empty;

                fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
                fastcgi_param  SERVER_SOFTWARE    nginx/$$nginx_version;

                fastcgi_param  REMOTE_ADDR        $$remote_addr;
                fastcgi_param  REMOTE_PORT        $$remote_port;
                fastcgi_param  SERVER_ADDR        $$server_addr;
                fastcgi_param  SERVER_PORT        $$server_port;
                fastcgi_param  SERVER_NAME        $$server_name;

                fastcgi_param  REDIRECT_STATUS    200;

                fastcgi_pass php:9000;
          }

          location ~ /\.ht {
              deny  all;
          }
        }
        EOF
        mkdir -p /var/www/configs/nginx/
        mkdir -p /var/www/logs/nginx/
        chown 1000:1000 /var/www/configs/nginx/ /var/www/logs/nginx/
        cat <<EOF > /var/www/configs/nginx/host.conf
        EOF
        nginx -g "daemon off;"

volumes:
  www_data:

networks:
  traefik-public:
    external: true
