version: '3.6'

services:
  cli:
    image: srvadm/mail:cli-dev
    restart: unless-stopped
    env_file:
      - .env

  dovecot:
    image: srvadm/mail:dovecot-dev
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik-public
      - default
    ports:
      - 143:143
      - 993:993
      - 110:110
      - 995:995
    volumes:
      - ../../data/${COMPOSE_PROJECT_NAME}/data:/var/vmail
      - ../../data/${TRAEFIK_COMPOSE_PROJECT_NAME}/certificates/${DOMAIN}:/etc/ssl/dovecot/
  
  mysql:
    image: srvadm/mail:mysql-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  nginx:
    image: srvadm/mail:nginx-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../../data/${COMPOSE_PROJECT_NAME}/www:/var/www
    networks:
      - traefik-public
      - default
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`webmail.${DOMAIN}`,`autoconfig.${DOMAIN}`,`autodiscover.${DOMAIN}`)
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=http
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.options=default-tls@file
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.domains[0].main=${DOMAIN}
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.domains[0].sans=${DOMAIN},mail.${DOMAIN},webmail.${DOMAIN},imap.${DOMAIN},smtp.${DOMAIN},autoconfig.${DOMAIN},autodiscover.${DOMAIN}
        - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80

  php:
    image: srvadm/mail:php-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../../data/${COMPOSE_PROJECT_NAME}/www:/var/www

  postfix:
    image: srvadm/mail:postfix-dev
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik-public
      - default
    ports:
      - 025:025
      - 587:587
    volumes:
      - ../../data/${TRAEFIK_COMPOSE_PROJECT_NAME}/certificates/${DOMAIN}:/etc/ssl/postfix/

  redis:
    image: redis:alpine
    volumes:
      - ../../data/${COMPOSE_PROJECT_NAME}/redis:/data

  rspamd:
    image: srvadm/mail:rspamd-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../../data/${COMPOSE_PROJECT_NAME}/rspamd:/var/lib/rspamd

volumes:
  mysql:

networks:
  traefik-public:
    external: true
  default:
    driver: overlay